remove admin build check in prs

diff --git a/.github/workflows/build-check.yml b/.github/workflows/build-check.yml
--- a/.github/workflows/build-check.yml
+++ b/.github/workflows/build-check.yml
@@ -17,7 +17,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       frontend: ${{ steps.filter.outputs.frontend }}
-      admin-portal: ${{ steps.filter.outputs.admin-portal }}
+      # admin-portal: ${{ steps.filter.outputs.admin-portal }}
       backend: ${{ steps.filter.outputs.backend }}
     steps:
       - name: Checkout code
@@ -30,8 +30,6 @@ jobs:
           filters: |
             frontend:
               - 'frontend/**'
-            admin-portal:
-              - 'admin-portal/**'
             backend:
               - 'backend/**'
 
@@ -64,32 +62,32 @@ jobs:
         working-directory: ./frontend
 
   # ---------------- LINT: ADMIN PORTAL ----------------
-  lint-admin:
-    name: Lint Admin Portal
-    runs-on: ubuntu-latest
-    needs: detect-changes
-    if: needs.detect-changes.outputs.admin-portal == 'true'
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # lint-admin:
+  #   name: Lint Admin Portal
+  #   runs-on: ubuntu-latest
+  #   needs: detect-changes
+  #   if: needs.detect-changes.outputs.admin-portal == 'true'
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
 
-      - name: setup pnpm
-        uses: pnpm/action-setup@v2
-        with:
-          version: 8
+  #     - name: setup pnpm
+  #       uses: pnpm/action-setup@v2
+  #       with:
+  #         version: 8
 
-      - name: Install dependencies
-        run: pnpm install
-        working-directory: ./admin-portal
+  #     - name: Install dependencies
+  #       run: pnpm install
+  #       working-directory: ./admin-portal
 
-      - name: Run Linter
-        run: pnpm run lint
-        working-directory: ./admin-portal
+  #     - name: Run Linter
+  #       run: pnpm run lint
+  #       working-directory: ./admin-portal
 
   # ---------------- LINT: BACKEND ----------------
   lint-backend:
@@ -157,41 +155,41 @@ jobs:
           fi
 
   # ---------------- ADMIN BUILD ----------------
-  admin-build:
-    name: Build Admin Portal
-    runs-on: ubuntu-latest
-    needs: [detect-changes, lint-admin]
-    if: needs.detect-changes.outputs.admin-portal == 'true'
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # admin-build:
+  #   name: Build Admin Portal
+  #   runs-on: ubuntu-latest
+  #   needs: [detect-changes, lint-admin]
+  #   if: needs.detect-changes.outputs.admin-portal == 'true'
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
 
-      - name: setup pnpm
-        uses: pnpm/action-setup@v2
-        with:
-          version: 8
+  #     - name: setup pnpm
+  #       uses: pnpm/action-setup@v2
+  #       with:
+  #         version: 8
 
-      - name: Install dependencies
-        run: pnpm install
-        working-directory: ./admin-portal
+  #     - name: Install dependencies
+  #       run: pnpm install
+  #       working-directory: ./admin-portal
 
-      - name: Build project
-        run: pnpm run build
-        working-directory: ./admin-portal
+  #     - name: Build project
+  #       run: pnpm run build
+  #       working-directory: ./admin-portal
 
-      - name: Verify build output
-        run: |
-          if [ -f "admin-portal/build/index.html" ]; then
-              echo "✅ Build output valid."
-          else
-              echo "❌ Build output missing!"
-              exit 1
-          fi
+  #     - name: Verify build output
+  #       run: |
+  #         if [ -f "admin-portal/build/index.html" ]; then
+  #             echo "✅ Build output valid."
+  #         else
+  #             echo "❌ Build output missing!"
+  #             exit 1
+  #         fi
 
   # ---------------- BACKEND TEST ----------------
   # backend-check:
